baseURL: "http://example.org/"
languageCode: en-us
title: Lenape Princeton Timetree
theme: timetree
paginate: 20

params:
  description: >-
    An alternate view of the history of Princeton incorporating
    Lenape and indigenous events and perspectives

# disable categories taxonomy included by default
taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - JSON
