baseURL: https://lenapetimetree.indigenous.princeton.edu/
languageCode: en-us
title: Lunaapahkiing Princeton Timetree
theme: timetree
paginate: 20
timeout: 45s # increase to allow time for image processing
googleAnalytics: G-E02J9KBNN6
enableRobotsTXT: true

params:
  description: >-
    Relations, Removals, Resurgence.
    An interactive timetree displaying interwoven histories of the
    Princeton University community and the Lenape peoples
    of Lunaapahkiing, “the land of the Lenape.”
  tagline: Relations, Removals, Resurgence
  publication_date: 2023
  citation_url: https://lenapetimetree.indigenous.princeton.edu/
  authors:
    - Himpele, Jeffrey
    - Koeser, Rebecca Sutton
    - Doroudian, Gissoo
    - Smith, Keely
  publisher: Center for Digital Humanities at Princeton
  rights: http://creativecommons.org/licenses/by/4.0/
  branches:
    - "Lands + Waters"
    - Communities
    - The University
    - Removals
    - Resistance + Resurgence
  visual_debug: false
  version: "1.1.0-dev"
  version_link: https://github.com/Princeton-CDH/lenape-timetree

# disable categories taxonomy included by default
taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - JSON

menu:
  footer:
    - name: Home
      title: Home
      pageRef: /
      weight: 1
    - name: About
      pageRef: /about
      weight: 2
    - name: Tag Index
      pageRef: /tags
      weight: 3
    - name: Resources
      pageRef: /resources
      weight: 4
    - name: Credits
      pageRef: /credits
      title: Credits
      weight: 5

# allow html markup in content
markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
